services:
  accounts:
    image: "saikumar311/easybank-accounts"
    container_name: "accounts-ms"
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank

  cards:
    image: "saikumar311/easybank-cards"
    container_name: "cards-ms"
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank

  loans:
    image: "saikumar311/easybank-loans"
    container_name: "loans-ms"
    ports:
      - "8084:8084"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
networks:
  easybank:
    driver: "bridge"